global:
  scrape_interval:
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s #global catch time
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "lib-api"
    static_configs:
      - targets: ["service.lib:4001"]
        labels:
          job: lib-api
          app: lib-api
          env: dev
  - job_name: "lib.rpc"
    static_configs:
      - targets: ["service.librpc:4000"]
        labels:
          job: lib.rpc
          app: lib.rpc
          env: dev
