// Code generated by goctl. DO NOT EDIT.
package types

type Merchant struct {
	Id       int64  `json:"id"`
	Name     string  `json:"name"`
	Status   int64  `json:"status"`
}

type MerchantAddReq struct {
	Name   int64 `json:"name"`
	Status int64 `json:"status"`
}

type MerchantUpdateReq struct {
	Id     int64 `json:"id"`
	Name   int64 `json:"name"`
	Status int64 `json:"status"`
}

type MerchantGetReq struct {
	Id int64 `json:"id"`
}

type MerchantDeleteReq struct {
	Id string `json:"id"`
}

type MerchantDeleteReply struct {
	Id string `json:"id"`
}

type MerchantSearchReq struct {
	Keyword  string `json:"keyword"`
	Page     int64  `json:"page"`
	Status   int64  `json:"status"`
	PageSize int64  `json:"pagesize"`
	OrderBy  string `json:"orderby"`
}

type MerchantSearchReply struct {
	Mechants []Merchant `json:"merchants"`
	IsEnd    bool       `json:"isend"`
	LastVal  int64      `json:"lastval"`
}

type MerchantUser struct {
	Id          int64  `json:"id"`
	FirstName   string `json:"firstname"`
	MidName     string `json:"midname"`
	LastName    string `json:"lastname"`
	Password    string `json:"password"`
	Telephone   string `json:"telephone"`
	Mobliephone string `json:"mobliephone"`
	MerchantId  int64  `json:"merchantid"`
	Status      int64  `json:"status"`
	HttpCode    int64  `json:"httpcode"`
	Message     string `json:"message"`
}

type MerchantUserAddReq struct {
	Id          int64  `json:"id"`
	FirstName   string `json:"firstname"`
	MidName     string `json:"midname"`
	LastName    string `json:"lastname"`
	Password    string `json:"password"`
	Telephone   string `json:"telephone"`
	Mobliephone string `json:"mobliephone"`
	MerchantId  int64  `json:"merchantid"`
}

type MerchantUserUpdateReq struct {
	FirstName   string `json:"firstname"`
	MidName     string `json:"midname"`
	LastName    string `json:"lastname"`
	Password    string `json:"password"`
	Telephone   string `json:"telephone"`
	Mobliephone string `json:"mobliephone"`
	MerchantId  int64  `json:"merchantid"`
}

type MerchantUserGetReq struct {
	Id int64 `json:"id"`
}

type MerchantUserDeleteReq struct {
	Id string `json:"id"`
}

type MerchantUserDeleteReply struct {
	HttpCode int64  `json:"httpcode"`
	Message  string `json:"message"`
}

type MerchantUserSearchReq struct {
	Keyword  string `json:"keyword"`
	Page     int64  `json:"page"`
	Status   int64  `json:"page"`
	PageSize int64  `json:"pagesize"`
	OrderBy  string `json:"orderby"`
}

type MerchantUserSearchReply struct {
	MechantUsers []MerchantUser `json:"merchantusers"`
	IsEnd        bool           `json:"isend"`
	LastVal      int64          `json:"lastval"`
	HttpCode     int64          `json:"httpcode"`
	Message      string         `json:"message"`
}

type MerchantUserLoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}
