// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"goecom/apps/lib/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/gettoken",
				Handler: gettokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/add",
				Handler: merchantaddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/update",
				Handler: merchantupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/get",
				Handler: merchantgetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/delete",
				Handler: merchantdeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/search",
				Handler: merchantsearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/add",
				Handler: merchantuseraddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/update",
				Handler: merchantuserupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/get",
				Handler: merchantusergetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/delete",
				Handler: merchantuserdeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/search",
				Handler: merchantusersearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/merchant/user/login",
				Handler: merchantuserloginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/store/add",
				Handler: storeaddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/store/update",
				Handler: storeupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/store/get",
				Handler: storegetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/store/delete",
				Handler: storedeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/store/search",
				Handler: storesearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/languages/add",
				Handler: languagesaddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/languages/update",
				Handler: languagesupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/languages/get",
				Handler: languagesgetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/languages/delete",
				Handler: languagesdeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/lib/languages/search",
				Handler: languagessearchHandler(serverCtx),
			},
		},
	)
}
