// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"goecom/apps/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/product/brand/add",
				Handler: brandaddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/product/brand/update",
				Handler: brandupdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/product/brand/get",
				Handler: brandgetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/product/brand/delete",
				Handler: branddeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/product/brand/search",
				Handler: brandsearchHandler(serverCtx),
			},
		},
	)
}
